### ISSUE TITLE
Reflinks do not work on ZFS 2.3.x

### ISSUE THREAD

**Issue by s0up4200** [autobrr/qui#1222]
### Discussed in https://github.com/autobrr/qui/discussions/1114

<div type='discussions-op-text'>

<sup>Originally posted by **cplieger** January  5, 2026</sup>
### Description

I have tested the reflink feature with openZFS 2.3.4 (truenas CE 25.10) and it did not create any links.
OpenZFS officially supports Reflinks (CoW) since 2.2 with refinements in 2.3. However OpenZFS does not implement FIDEDUPERANGE. Instead, it only implements FICLONERANGE which blindly clones blocks without verifying they are identical first.

I suspect that this is why Qui does not function on ZFS.

### Steps to reproduce

1. run truenas CE or any other openZFS implementation
2. use reflinks
3. query the ZFS object details for both file inodes using zdb -ddddd <pool>/<dataset> <inode_number>
4. check if the Data Virtual Address match.

### Environment

```text
qui 1.12
qbit 5.14
docker
Truenas CE 25.10
```

### Checklist

- [X] I have searched existing discussions and issues
- [X] I have checked the documentation</div>
